### ISSUE TITLE
Installation in Medusa v2

### ISSUE THREAD

**Issue by Hoolaf** [RSC-Labs/medusa-store-analytics#40]
Hi guys am trying to install [medusa-store-analytics](https://github.com/RSC-Labs/medusa-store-analytics) but i have this error all times
![Capture d'écran 2025-01-03 015823](https://github.com/user-attachments/assets/2d05efb3-f3c7-489e-a976-6cc6c8a60b25)

**Comment by BeyondOT** [comment]
I have the exact same issue

**Comment by Hoolaf** [comment]
Yeah i dont know why

**Comment by radoslaw-sz** [comment]
hi all - thank you for raising this issue!
Could someone provide following information to debug this issue:
- `medusa-config.js` content
- directory structure where you pasted the code of this plugin

**Comment by BeyondOT** [comment]
```typescript
import { loadEnv, defineConfig } from "@medusajs/framework/utils";

loadEnv(process.env.NODE_ENV || "development", process.cwd());

module.exports = defineConfig({
  admin: {
    backendUrl: process.env.MEDUSA_BACKEND_URL,
  },
  modules: [
    { resolve: "./modules/store-analytics" },
    {
      key: "eventBus",
      resolve: "@medusajs/event-bus-redis",
      options: {
        redisUrl: process.env.EVENTS_REDIS_URL,
      },
    },
    {
      resolve: "@medusajs/medusa/workflow-engine-redis",
      options: {
        redis: {
          url: process.env.REDIS_URL,
        },
      },
    },
    {
      resolve: "@medusajs/medusa/file",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/file-s3",
            id: "s3",
            options: {
              file_url: process.env.S3_FILE_URL,
              access_key_id: process.env.S3_ACCESS_KEY_ID,
              secret_access_key: process.env.S3_SECRET_ACCESS_KEY,
              region: process.env.S3_REGION,
              bucket: process.env.S3_BUCKET,
              endpoint: process.env.S3_ENDPOINT,
              // other options...
            },
          },
        ],
      },
    },
  ],

  projectConfig: {
    workerMode: process.env.MEDUSA_WORKER_MODE as "shared" | "worker" | "server",
    databaseUrl: process.env.DATABASE_URL,
    redisUrl: process.env.REDIS_URL,
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
  },
});
```

And for the directory structure I just pasted all the files in the src directory
![image](https://github.com/user-attachments/assets/6d01bdda-ac25-4f87-9e5c-e876388a3595)

**Comment by radoslaw-sz** [comment]
hi @BeyondOT  - could you please also check which version of Medusa you are using? I mean which Medusa version you have in your package.json.

**Comment by Hoolaf** [comment]
My am  USing [v2.1.3](https://github.com/medusajs/medusa/releases/tag/v2.1.3)

**Comment by BeyondOT** [comment]
I am using v2.1.3

**Comment by radoslaw-sz** [comment]
thanks @BeyondOT and @Hoolaf  - I will take a look at this in the next days and I will be back to you

**Comment by radoslaw-sz** [comment]
hi @BeyondOT  and @Hoolaf  - unfortunately I am not able to reproduce this issue on my side - it works constantly.
I just pushed possible fix (it is a blind shot), so please copy the newest code from the repository and test on your side.
If it won't work - then we would need to closely debug this issue by modifying a code and check what is going on.

PS. This module follows the approach mentioned here: https://docs.medusajs.com/learn/fundamentals/modules/multiple-services.

**Comment by BeyondOT** [comment]
hi @radoslaw-sz  I still have the same issue. To make sure that it wasnt related to my own project, I have created a brand new medusa project with `npx create-medusa-app@latest` and just pasted the content of src/ folder from the v2 folder into the src folder of the new project and still, same issue. 

In order to debug this more easily,I pushed the project to github here it is: [https://github.com/BeyondOT/analytics-test](https://github.com/BeyondOT/analytics-test)

**Comment by radoslaw-sz** [comment]
hi @BeyondOT  - that was really useful!

Because of the "copy code" approach I totally forgot about `package.json` - it needs to be updated.
Please paste these packages into your `package.json` dependencies:

```
    "@medusajs/icons": "^2.1.3",

    "@mui/material": "^6.1.2",
    "react-hook-form": "^7.53.0",
    "@emotion/react": "^11.13.3",
    "@emotion/styled": "^11.13.0",

    "pdfkit": "^0.15.1",
    "recharts": "^2.13.3"
```

I will update the readme in a free time - generally it should not have happened when Medusa will start support plugins out of the box because above packages will come together with plugin package.

**Comment by Hoolaf** [comment]
OH Thank you so much

**Comment by radoslaw-sz** [comment]
hi @Hoolaf  - thanks for the response, @BeyondOT  - could you please confirm that it works on your side? I would like to close this issue.

**Comment by BeyondOT** [comment]
Hi @radoslaw-sz , sorry for the late reply had a busy couple of days. Yes it works perfectly thank you !
